using StateButton.Handler;

namespace StateButton;

/// <summary>
/// This class contains CustomSwitch <see cref="MauiAppBuilder"/> extensions.
/// </summary>
public static partial class AppBuilderExtensions
{
	/// <summary>
	/// Initializes the Switch control
	/// </summary>
	/// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/>.</param>
	/// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="StateButton"/>.</returns>
	public static MauiAppBuilder UseStateButton(this MauiAppBuilder builder)
	{
		builder.ConfigureMauiHandlers(h => h.AddHandler<StateButton, StateButtonHandler>());

#if ANDROID
		StateButtonHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
		{
			if (view is StateButton stateButton)
			{
				CustomContentViewGroup platformView = (CustomContentViewGroup)handler.PlatformView;

				platformView.Pressed1 += (_, e) => stateButton.InternalPressed();
				platformView.Released += (_, e) => stateButton.InternalReleased();
				platformView.Clicked += (_, e) => stateButton.InternalClicked();
			}
		});
#elif IOS
		StateButtonHandler.Mapper.AppendToMapping("MyCustomization", (handler, view) =>
		{
			if (view is StateButton stateButton)
			{
				CustomContentView platformView = (CustomContentView)handler.PlatformView;

				platformView.Pressed += (_, e) => stateButton.InternalPressed();
				platformView.Released += (_, e) => stateButton.InternalReleased();
				platformView.Clicked += (_, e) => stateButton.InternalClicked();
			}
		});
#endif

		return builder;
	}
}