using IeuanWalker.Maui.StateButton.Handler;

namespace IeuanWalker.Maui.StateButton;

/// <summary>
/// This class contains CustomSwitch <see cref="MauiAppBuilder"/> extensions.
/// </summary>
public static class AppBuilderExtensions
{
	/// <summary>
	/// Initializes the StateButton control
	/// </summary>
	/// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/>.</param>
	/// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="StateButton"/>.</returns>
	public static MauiAppBuilder UseStateButton(this MauiAppBuilder builder)
	{
		builder.ConfigureMauiHandlers(h => h.AddHandler<StateButton, StateButtonHandler>());

		return builder;
	}
}